env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi

language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

sudo: false
cache:
  directories:
    - "$HOME/.composer/cache"

before_script:
  - phpenv config-rm xdebug.ini || return 0

install:
  - travis_retry composer install --no-progress --prefer-dist

script:
  - vendor/bin/tester -p $PHP_BIN tests -s

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
  include:
    - name: Lowest Dependencies
      env: PHP_BIN=php
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable

    - stage: Code Sniffer
      script:
        - vendor/bin/phpcs --standard=phpcs.xml --encoding=utf-8 -sp src/ tests/

    - stage: Static Analysis
      script:
        - vendor/bin/phpstan analyse -c phpstan.neon -l 7 src/

    - stage: Code Coverage
      script:
        - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
      after_script:
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
        - php coveralls.phar --verbose --config .coveralls.yml

  allow_failures:
    - stage: Static Analysis
    - stage: Code Coverage
    - stage: Code Sniffer

notifications:
  email: false